### ISSUE TITLE
Documentation outdated for the container labels

### ISSUE THREAD

**Issue by remyduthu** [bleemeo/glouton#17]
We can use Kubernetes annotations (or Docker labels) to disable Glouton for a specific pod. [In the documentation](https://docs.bleemeo.com/metrics-sources/docker), it is written that the `glouton.enabled` annotation should be used for that, but [in the code](https://github.com/bleemeo/glouton/blob/57142513a6e471f75804aaf0cbb20c17479620b8/facts/container-runtime/kubernetes/testdata/k8s.yml#L64) the `glouton.enable` annotation is used instead.

**Comment by lporcheron** [comment]
Good catch @remyduthu ! We will get that fix. Thanks for the heads-up!

**Comment by lporcheron** [comment]
We updated our documentation and also took this opportunity to make sure we are consistent using enable/enabled.
