### ISSUE TITLE
Agent Manual Installation not working

### ISSUE THREAD

**Issue by OpsDevEd** [bleemeo/glouton#29]
I just signed up to try your service but i have problems installing the agent on almalinux.
I followed the Agent Manual Installation steps as the script did not work.

Problem 1:

$ wget https://packages.bleemeo.com/bleemeo-agent/binary/glouton-linux-$(uname -m).bin
$ sudo mv glouton-$(uname -m).bin /usr/local/sbin/glouton

-> The second command does not contain -linux- and therefore gives an error while copy pasting the command to the terminal

Problem 2:

Starting the agent fails with command not found

-> I had to make the bin executable by executing 'chmod +x /usr/local/sbin/glouton'

Problem 3:

Starting the agent gives:
Error while loading configuration: stat C:\ProgramData\glouton\conf.d: permission denied

-> looks like a windows path while i am on Linux

**Comment by lporcheron** [comment]
Hi @OpsDevEd,

Thanks for your ticket.

Thanks for highlighting Problems 1 & 2, we have just updated the doc to fix those two issues. 

On which architecture are you trying to install agent? On a x64 machine, I can't reproduce Problem 3:
`
$ wget https://packages.bleemeo.com/bleemeo-agent/binary/glouton-linux-$(uname -m).bin
--2022-08-05 11:39:31--  https://packages.bleemeo.com/bleemeo-agent/binary/glouton-linux-x86_64.bin
Resolving packages.bleemeo.com (packages.bleemeo.com)... 15.188.168.190
Connecting to packages.bleemeo.com (packages.bleemeo.com)|15.188.168.190|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65667072 (63M) [application/octet-stream]
Saving to: ‘glouton-linux-x86_64.bin’

glouton-linux-x86_64.bin                                          90%[=======================================================================================================================================>                ]  56.41M  4.05MB/s    eta 2s glouton-linux-x86_64.bin                                          91%[==========================================================================================================================================>             ]  57.48M  4.09MB/s    eta 1s glouton-linux-x86_64.bin        100%[=====================================================>]  62.62M  5.06MB/s    in 14s

2022-08-05 11:39:45 (4.37 MB/s) - ‘glouton-linux-x86_64.bin’ saved [65667072/65667072]

$ chmod +x glouton-linux-x86_64.bin
$ ./glouton-linux-x86_64.bin
2022/08/05 11:41:06 Starting agent version 22.07.25.102122 (commit d0da020c5d76acf41c6bf4629acf10288522f014)
2022/08/05 11:41:06 Starting API on 127.0.0.1:8015 ✔️
2022/08/05 11:41:06 To access the local panel connect to http://127.0.0.1:8015 🌐
`

As a side note, I would recommend using the package installation (if you don't want to use the wget method), using the CentOS installation section:
https://docs.bleemeo.com/agent/installation/#installation-on-centos-with-native-packages

We have customers using those packages on Almalinux and you should not face any issues.

Let us know if you still face the issue with a specific architecture.

**Comment by OpsDevEd** [comment]
Hi Lionel,

Thanks for the quick reply.

uname -m gives: x86_64

NAME="AlmaLinux"
VERSION="8.6 (Sky Tiger)"
ID="almalinux"
ID_LIKE="rhel centos fedora"

For #3, The only difference on your try to reproduce is that i use sudo, so i am logged on as user X and sudo the commands. The commands are exact the same and i guess sudo should not matter.

The CentOS native package is indeed working for me on this server.

Thanks!

br, Eddy

**Comment by lporcheron** [comment]
We will check the message you had, but all is good on your side right now?

**Comment by OpsDevEd** [comment]
Yes, I installed 2 agents successfully.
